pipeline {
    agent any

    environment {
        REGISTRY = "harbor.example.com/devops-demo"
        IMAGE = "web-demo"
        TAG = "${BUILD_NUMBER}"
        GIT_CREDENTIALS = "gitea-credit"
    }

    stages {
        stage('Checkout') {}
        stage('Build Image') {}
        stage('Scan Image') {}
        stage('Push Image') {}
        stage('Update K8s YAML') {}
    }
}
