ETCD_NAME=etcd1
ETCD_DATA_DIR=/data/etcd

ETCD_CERT_FILE=
ETCD_KEY_FILE=
ETCD_TRUSTED_CA_FILE=
ETCD_CLIENT_CERT_AUTH=true
ETCD_LISTEN_CLIENT_URLS=https://<this-etcd-ip>:2379
ETCD_ADVERTISE_CLIENT_URLS=https://<this-etcd-ip>:2379

ETCD_PEER_CERT_FILE=
ETCD_PEER_KEY_FILE=
ETCD_PEER_TRUSTED_CA_FILE=
ETCD_LISTEN_PEER_URLS=https://<this-etcd-ip>:2380
ETCD_INITIAL_PEER_URLS=https://<this-etcd-ip>:2380

ETCD_INITIAL_CLUSTER_TOKEN=
ETCD_INITIAL_CLUSTER="etcd1=https://<etcd1-ip>:2380,etcd2=,etcd3="
ETCD_INITIAL_CLUSTER_STATE=new
